<?php

namespace VenuesBundle\Repository;

/**
 * EmailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
