<?php

namespace VenuesBundle\Repository;

/**
 * VenuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenuesRepository extends \Doctrine\ORM\EntityRepository
{
}
